name: Test
on:
  workflow_call:

jobs:
  code-formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: cargo fmt --check

  code-linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-features --workspace --tests -- --warn clippy::all --warn clippy::nursery

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: downaload stable rust channel manifest
        run: curl -o channel-rust-stable.toml -sSL https://static.rust-lang.org/dist/channel-rust-stable.toml
      - name: Apply yq filter on manifest 
        id: get_rust_version_string_from_toml
        uses: mikefarah/yq@master
        with:
          cmd:  yq -oy -p toml '.pkg.rust.version' channel-rust-stable.toml
      - name: Reuse a variable obtained in another step
        run: |
          rm channel-rust-stable.toml
          echo "${{ steps.get_rust_version_string_from_toml.outputs.result }}"
      - name: Get latest Rust version
        id: get_rust_version
        run: |
          latest_version=$(echo "${{ steps.get_rust_version_string_from_toml.outputs.result }}" |  cut -d' ' -f1)
          latest_version=${latest_version#v}  # Remove 'v' prefix if exists
          echo "latest_version=$latest_version" >> $GITHUB_ENV
          echo "latest_version=$latest_version"
          echo "latest_version=$latest_version" >> $GITHUB_OUTPUT
      - name: Run cargo test
        run: cargo test
